import Footer from "@/components/Footer";
import { LoadUserState } from "@/components/LoadUserState";
import NavBar from "@/components/NavBar";
import ThemeProvider from "@/components/ThemeProvider";
import { Toaster } from "@/components/ui/sonner";
import type { Metadata } from "next";
import { Ubuntu } from "next/font/google";
import "./globals.css";

const ubuntu = Ubuntu({
    subsets: ["latin"],
    weight: ["400", "500", "700"],
    variable: "--font-ubuntu",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" suppressHydrationWarning>
            <body className={`${ubuntu.variable} antialiased`}>
                <ThemeProvider
                    attribute="class"
                    defaultTheme="system"
                    enableSystem
                    disableTransitionOnChange
                >
                    <Toaster position="top-right" />
                    <div className="max-w-xl w-full mx-auto px-4 lg:px-0">
                        <NavBar />
                        <div className="">{children}</div>
                        <Footer />
                    </div>
                    <LoadUserState />
                </ThemeProvider>
            </body>
        </html>
    );
}
